# Generated by Django 2.2.4 on 2020-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200110_1113'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwahaeuser',
            name='favorite_ingredient',
        ),
        migrations.RemoveField(
            model_name='hwahaeuser',
            name='favorite_products',
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='favs_ingredients',
            field=models.ManyToManyField(null=True, related_name='users', to='products.Ingredient'),
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='favs_products',
            field=models.ManyToManyField(null=True, related_name='users', to='products.Product'),
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='password',
            field=models.CharField(default='abcd', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwahaeuser',
            name='username',
            field=models.CharField(default='korea', error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
